package com.example.danmuapiapp.domain.model

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class CoreLogNoiseFilterTest {

    @Test
    fun `removes complete server access group generated by polling api logs`() {
        val blocks = listOf(
            "[17:35:54][核心][系统][Info] [system] [Server] request url: \"http://127.0.0.1:9321/87654321/api/logs\"",
            "[17:35:54][核心][系统][Info] [system] [Server] request path: /87654321/api/logs",
            "[17:35:54][核心][系统][Info] [system] [Server] client ip: 127.0.0.1",
            "[17:35:54][核心][系统][Info] [system] [Server] /api/logs",
            "[17:35:55][核心][系统][Info] [system] [Server] request path: /87654321/api/v2/comment"
        )

        val filtered = CoreLogNoiseFilter.removeLogEndpointPollingBlocks(blocks)

        assertEquals(listOf(blocks.last()), filtered)
    }

    @Test
    fun `removes app internal reqrecords and cache animes polling groups`() {
        val blocks = listOf(
            "[19:00:06][核心][系统][Info] [system] [Server] request url: \"http://127.0.0.1:9321/admin-token/api/reqrecords\"",
            "[19:00:06][核心][系统][Info] [system] [Server] request path: /admin-token/api/reqrecords",
            "[19:00:06][核心][系统][Info] [system] [Server] client ip: ***.*.*.*",
            "[19:00:06][核心][缓存][Info] [Cache] getLocalCaches start.",
            "[19:00:06][核心][缓存][Info] [Cache] Restored lastSelectMap from local cache with 0 entries",
            "[19:00:06][核心][缓存][Info] [Cache] getLocalCaches completed successfully.",
            "[19:00:06][核心][系统][Info] [system] [Server] request url: \"http://127.0.0.1:9321/admin-token/api/cache/animes\"",
            "[19:00:06][核心][系统][Info] [system] [Server] request path: /admin-token/api/cache/animes",
            "[19:00:06][核心][系统][Info] [system] [Server] client ip: ***.*.*.*",
            "[19:00:06][核心][系统][Info] [system] [Server] /api/cache/animes",
            "[19:00:07][核心][合并][Info] [Merge-Check] real danmu diagnostic"
        )

        val filtered = CoreLogNoiseFilter.removeLogEndpointPollingBlocks(blocks)

        assertEquals(listOf(blocks.last()), filtered)
    }

    @Test
    fun `does not remove normal api request client ip logs`() {
        val blocks = listOf(
            "[17:35:54][核心][系统][Info] [system] [Server] request url: \"http://127.0.0.1:9321/87654321/api/v2/comment?id=1\"",
            "[17:35:54][核心][系统][Info] [system] [Server] request path: /87654321/api/v2/comment",
            "[17:35:54][核心][系统][Info] [system] [Server] client ip: 127.0.0.1",
            "[17:35:54][核心][系统][Info] [system] [Server] /api/v2/comment"
        )

        val filtered = CoreLogNoiseFilter.removeLogEndpointPollingBlocks(blocks)

        assertEquals(blocks, filtered)
    }

    @Test
    fun `does not remove cache init info after real danmu request`() {
        val blocks = listOf(
            "[19:00:06][核心][系统][Info] [system] [Server] request url: \"http://127.0.0.1:9321/87654321/api/v2/comment/123?format=json\"",
            "[19:00:06][核心][系统][Info] [system] [Server] request path: /87654321/api/v2/comment/123",
            "[19:00:06][核心][系统][Info] [system] [Server] client ip: 127.0.0.1",
            "[19:00:06][核心][系统][Info] [system] [Server] /api/v2/comment/123",
            "[19:00:06][核心][缓存][Info] [Cache] getLocalCaches start."
        )

        val filtered = CoreLogNoiseFilter.removeLogEndpointPollingBlocks(blocks)

        assertEquals(blocks, filtered)
    }

    @Test
    fun `does not remove clear logs endpoint because it is an explicit user action`() {
        val blocks = listOf(
            "[17:35:54][核心][系统][Info] [system] [Server] request url: \"http://127.0.0.1:9321/87654321/api/logs/clear\"",
            "[17:35:54][核心][系统][Info] [system] [Server] request path: /87654321/api/logs/clear",
            "[17:35:54][核心][系统][Info] [system] [Server] client ip: 127.0.0.1"
        )

        val filtered = CoreLogNoiseFilter.removeLogEndpointPollingBlocks(blocks)

        assertEquals(blocks, filtered)
    }

    @Test
    fun `removes partial unambiguous api logs lines without hiding standalone client ip`() {
        val blocks = listOf(
            "[17:35:54][核心][系统][Info] [system] [Server] request path: /87654321/api/logs",
            "[17:35:54][核心][系统][Info] [system] [Server] client ip: 127.0.0.1"
        )

        val filtered = CoreLogNoiseFilter.removeLogEndpointPollingBlocks(blocks)

        assertEquals(1, filtered.size)
        assertTrue(filtered.single().contains("client ip"))
    }
}
